### ISSUE TITLE
doc: is there official igniteui-angular2 document available?

### ISSUE THREAD

**Issue by JiaLiPassion** [IgniteUI/igniteui-angular-wrappers#158]
I can't find the official document of igniteui-angular2, I can only find some samples in this repo, is there any plan to release the official document? Thanks!

**Comment by kdinev** [comment]
@JiaLiPassion We're in the process of adding Angular code example for each sample in our samples browser. Docs are also in the pipeline.

**Comment by JiaLiPassion** [comment]
@kdinev, thank you for your reply! Hope to see the ignite for angular2 document later!

**Comment by mpavlinov** [comment]
I'm closing this one, because it's very old and we are not planning to work on it. We now have the [Ignite UI for Angular](https://github.com/IgniteUI/igniteui-angular) product in place.
