### ISSUE TITLE
Getting error when using chaining loader method

### ISSUE THREAD

**Issue by igDivya** [IgniteUI/igniteui-angular-wrappers#166]
[Loader.zip](https://github.com/IgniteUI/igniteui-angular2/files/1086201/Loader.zip)
Customer is getting below error when using chaining method for using igloader.

Error: “Property ‘load’  does not exist on the type ‘Void’ ”

Using below code:
 $.ig.loader({
        scriptPath: 'Scripts/build/infragistics/js',
        cssPath: 'CSS/build/infragistics/css'
           }).load('igEditors', () => report.initigEditors());

Please find the attached image file for more information.
[Loader.zip](https://github.com/IgniteUI/igniteui-angular2/files/1086209/Loader.zip)
![Uploading Loader.png…]()

case No: 'CAS-184935-Y4F5X8'

**Comment by dkamburov** [comment]
This is resolved with the latest version of the [@types/ignite-ui](https://www.npmjs.com/package/@types/ignite-ui) (18.1.1)
