### ISSUE TITLE
igniteui.d.ts does not have the definition of $.ig.regional . 

### ISSUE THREAD

**Issue by igDivya** [IgniteUI/igniteui-angular-wrappers#169]
Using below code in the type-script file giving me design time error

Code:
$.ig.regional.defaults;
Please find the attached image of the error for more information.

Actual result:

Getting below Error:
“Property 'regional' does not exist on type 'IgniteUIStatic'.”

Expected result:
Regional should be defined in igniteui.d.ts file.

Something like this:
interface IgniteUIStatic {
    regional: {
        defaults: {
            datePattern: string;
            timePattern: string;
        }
    }
}
Case No:CAS-184944-K5Z1G4
[Regional.zip](https://github.com/IgniteUI/igniteui-angular2/files/1089236/Regional.zip)

**Comment by dkamburov** [comment]
This is resolved with the latest version of the [@types/ignite-ui](https://www.npmjs.com/package/@types/ignite-ui) (18.1.1)
