### ISSUE TITLE
igTree selectionChanged event interface is not correct

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular-wrappers#171]
The `IgTree` interface in `igniteui.ts` defines the event like:
```ts
selectionChanged?: SelectionChangedEvent;
```
But the `SelectionChangedEvent` and  `SelectionChangedEventUIParam` actually seem to belong to the Combo and are not compatible with the Tree, so the handler will fail standard type checking and compilation:
![image](https://user-images.githubusercontent.com/3198469/27957363-d9d5d5d0-6326-11e7-8a8a-1b76587fcdda.png)

I'm guessing the shared `SelectionChangedEvent` was not intended and should be split into Combo/Tree versions?
@skrustev / @dkamburov  Can you guys have a look?

**Comment by damyanpetev** [comment]
P.S. This can be be worked around by forcing the parameter type as `ui: any` or using the markup binding, but both options loose on the Intellisense side.

**Comment by dkamburov** [comment]
This is resolved with the latest version of the [@types/ignite-ui](https://www.npmjs.com/package/@types/ignite-ui) (18.1.1)
