### ISSUE TITLE
Module not found: Error: Can't resolve 'igniteui-angular-wrappers' (v5.0.5)

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular-wrappers#241]
### Description  
Module not found: Error: Can't resolve 'igniteui-angular-wrappers' (v5.0.5)

### Steps to reproduce  

1. Create a new app
>ng new my-app1
>cd my-app1
>npm install @infragistics/ignite-ui-full
>npm install igniteui-angular-wrappers

2. Copy the following files from the attached sources.zip
index.html: to "src" folder
app.component.html, app.component.ts, app.module.ts: to "src/app" folder

3. npm start

### Result  
Module not found: Error: Can't resolve 'igniteui-angular-wrappers' (v5.0.5)

### Expected result  
Such an error should not occur.

### Attachments  
Attach a sample if available, an
[sources.zip](https://github.com/IgniteUI/igniteui-angular-wrappers/files/1642147/sources.zip)
d screenshots, if applicable.  

### Notes

igniteui-angular-wrappers/dist/npm/package.json still has

    "main": "bundles/igniteui-angular2.umd.js",

This might be the cause.

**Comment by mpavlinov** [comment]
@norikois You're correct. Next time you can do a PR.

**Comment by mpavlinov** [comment]
PR is merged. Closing this one.
