### ISSUE TITLE
Rename igniteui.angular2

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular-wrappers#249]
### Description  
The repository has been renamed from igniteui-angular2 to igniteui-angular-wrappers.
But there are still `igniteui.angular2` name.

### Result  
- File name
  - igniteui-angular-wrappers/src/igniteui.angular2.ts

- All the import statement
  > import { xxx } from '**/src/igniteui.angular2';

- In the config files
  - igniteui-angular-wrappers/dist/npm/package.json
    >  "types": "igniteui.angular2.d.ts",
  - igniteui-angular-wrappers/rollup.config.umd.js
    > entry: 'src/igniteui.angular2.ts',
  - igniteui-angular-wrappers/tsconfig-aot.json
    > "src/igniteui.angular2.ts"

- In the README
  - igniteui-angular-wrappers/README.md
  - igniteui-angular-wrappers/dist/npm/README.md
    > Use the components found in src\igniteui.angular2.ts to use ...

### Expected result  
- File name
  - igniteui-angular-wrappers/src/igniteui.angular.wrappers.ts

- All the import statement
  > import { xxx } from '**/src/igniteui.angular.wrappers';

- In the config files
  - igniteui-angular-wrappers/dist/npm/package.json
    >  "types": "igniteui.angular.wrappers.d.ts",
  - igniteui-angular-wrappers/rollup.config.umd.js
    > entry: 'src/igniteui.angular.wrappers.ts',
  - igniteui-angular-wrappers/tsconfig-aot.json
    > "src/igniteui.angular.wrappers.ts"

- In the README
  - igniteui-angular-wrappers/README.md
  - igniteui-angular-wrappers/dist/npm/README.md
    > Use the components found in src\igniteui.angular.wrappers.ts to use ...

**Comment by tkiryu** [comment]
I understand there is a huge impact, though...

**Comment by kdinev** [comment]
The main files should in fact be called `main.ts` and not `igniteui.angular.wrappers.ts`.

**Comment by tkiryu** [comment]
Thank you for pointing out my mistake!
