### ISSUE TITLE
IgHierarchicalGrid shows all records in the first load with local paging

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular-wrappers#250]
### Description  
 IgHierarchicalGrid is configured with local paging and page size: 10. When loading an Observable data of 100 records, it's showing all records in the first load.

### Steps to reproduce  

1. npm install
2. ng serve
3. open your browser on the localhost which Development Sever is listening to

### Result  
igHierarchicalGrid loads all data records on initial load

### Expected result  
igHierarchicalGrid should load only 10 records on initial load

### Attachments  
[hierarchicalGridPaging.zip](https://github.com/IgniteUI/igniteui-angular-wrappers/files/1720117/hierarchicalGridPaging.zip)

**Comment by ishibashish** [comment]
is there any update on this issue? @dkamburov

**Comment by dkamburov** [comment]
We are currently going over huge performance improvements with two way data binding and we are expecting behavioral changes. Until this get's resolved use the dataBind method to repaint the paging feature properly.

**Comment by dkamburov** [comment]
This seems to be resolved with the latest version - 5.1.0-beta.0
[hierarchicalGridPaging_latest.zip](https://github.com/IgniteUI/igniteui-angular-wrappers/files/1750949/hierarchicalGridPaging_latest.zip)
