### ISSUE TITLE
igCombo's Clear button does not clear ngModel value.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular-wrappers#251]
### Description  
igCombo's Clear button does not clear ngModel value.

### Steps to reproduce  

1. Unzip the attached sample, 'npm install', 'npm install igniteui-angular-wrappers' and npm start.
2. Open the dropdown list and select one of the items: 'blue', 'red' or 'yellow'.
3. Click 'x' button.

### Result  
ngModel value is not cleared.

### Expected result  
ngModel value should be cleared.

### Note
This issue is reproducible with IgniteUI for Javascript v17.1, but not with v17.2.

### Attachments  
[my-app3.zip](https://github.com/IgniteUI/igniteui-angular-wrappers/files/1726452/my-app3.zip)

**Comment by norikois** [comment]
Sorry, but after I investigated it further, the reproducible sample is not accurate. The sample's package.json has both igniteui-angular2 and igniteui-angular-wrappers and the symptom looks like occurring because of this.
As long as just igniteui-angular-wrappers are used, this symptom does not occur with both v17.1 and v17.2.

**Comment by kdinev** [comment]
@norikois Closing the issue.
