### ISSUE TITLE
Ig-Combo clear Converts model to Array

### ISSUE THREAD

**Issue by rinkeshmistry** [IgniteUI/igniteui-angular-wrappers#253]
I download sample of your current version **igniteui-angular-wrappers-5.0.7**
while i select any value from drop down and clear it ..it converts ngModel to array .  

I attached screen shot of issue . 

1. While selecting value model is number

![issue-image-1](https://user-images.githubusercontent.com/26963941/36583029-dc240bda-1899-11e8-836d-026230065554.png)

2.after clearing value .. it converts to array . 
![image](https://user-images.githubusercontent.com/26963941/36583039-e4953294-1899-11e8-95c4-abd58eb24351.png)

### Expected result  
It should be number if our model is numeric. 
It should be string if our model is string. 
it should be array if our model is array

**Comment by dkamburov** [comment]
It is an empty array, because this is the model of igCombo when the value is cleared. I believe, it is done for consistency when there is multiple selection.

**Comment by rinkeshmistry** [comment]
it is working fine for multi selection .
but if it is single selection then model will be set to null or undefined (in any cases )

if u convert model to array and pass model object or particular model to server side then it throws error .
