### ISSUE TITLE
addRow and deleteRow method are unexpectedly defined in IgGridBase<Model> class

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular-wrappers#255]
### Description  
addRow and deleteRow method are unexpectedly defined in IgGridBase<Model> class.

### Steps to reproduce  

1. Open iggridbase.d.ts and observe IgGridBase<Model> class

### Result  
addRow and deleteRow are defined.

### Expected result  
addRow and deleteRow are not defined as these methods are already defined in IgGridUpdatingFeature class.

**Comment by dkamburov** [comment]
`addRow` and `deleteRow` in IgGridBase are different from `addRow` and `deleteRow` in IgGridUpdatingFeature. Methods in IgGridBase are part of the data binding capabilities of the grids and are used when changes into the data source are detected. If you want to use the updating functionality you should use the methods from IgGridUpdatingFeature.

**Comment by dkamburov** [comment]
@ymita If you have further questions, please re-open the issue

**Comment by dkamburov** [comment]
This is is getting resolved with issue #257, unfortunately there is no recently tagged version so the fix is not publicly available.

**Comment by dkamburov** [comment]
Resolved in 6.0.0 version 
[hierarchicalGrid.zip](https://github.com/IgniteUI/igniteui-angular-wrappers/files/2053550/hierarchicalGrid.zip)

**Comment by ymita** [comment]
@dkamburov thank you for letting me know. I confirm it is fixed.
