### ISSUE TITLE
Cannot instantiate the igScheduler using the igniteui-angular-wrappers

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular-wrappers#256]
### Description  
Add a simple igScheduler on the page using the Ignite Ui Angular wrappers:
```
<ig-scheduler
	#scheduler1
	widgetId = "scheduler1"
	height = "650px"
	width = "100%"
	[options] = "options">
</ig-scheduler>
```
### Result  
Trying to run it results in an error, check the browser dev tools console:
```
"TypeError: Cannot read property 'prototype' of undefined
    at IgSchedulerComponent.IgControlBase (VM4378 igcontrolbase.ts!transpiled:74)"
```

**Comment by dkamburov** [comment]
Can you make sure you have igScheduler refences included(infragistics.scheduler-bundled.js)?
I made a [plunker](https://plnkr.co/edit/htzvuR?p=preview) and it seems to be working as expected.

**Comment by hanastasov** [comment]
Of course this missing reference is the reason, a rookie mistake, sorry ! L:0 Closing the issue.
