### ISSUE TITLE
Ig-grid rebind issue for remote data

### ISSUE THREAD

**Issue by rinkeshmistry** [IgniteUI/igniteui-angular-wrappers#260]
I am using ignite-ui in angular 5 & dotnet core 2 application. Here i have facing issue regarding rebinding datasource in ig-grid. currently i am upgrading my application from angular 4 to 5. so my old application  had **"igniteui-angular-wrappers": "4.1.1"** now its **"igniteui-angular-wrappers": "5.0.7"**. In old version there wasn't issue of rebinding datasource but in new version its happen. In edit mode when any record was updated that time data was hidden and add time only added record display. 

Here i found issue in **IgGridBase.prototype.ngDoCheck** method. In new version some changes compare to old version. When i did change that method thats working fine in my application.

![old_code](https://user-images.githubusercontent.com/26963941/37961431-e711d72a-31d5-11e8-9d64-690fcc003f82.PNG)

This is original code of ngDoCheck method. Now i was changing code as old version. i highlight that line.

![new_code](https://user-images.githubusercontent.com/26963941/37961521-22e81836-31d6-11e8-97c1-e4596aa0a180.PNG)

So if you pull that code in new release its will be great for us.

Thanks,
Rinkesh Mistry.

**Comment by dkamburov** [comment]
@rinkeshmistry Can you confirm if this is resolved with #266

**Comment by dkamburov** [comment]
Should be resolved with the later versions, if you have additional questions on this, please re-open it.
