### ISSUE TITLE
Make sure the element is in DOM, before destroying it.

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular-wrappers#268]
### Description  
Make sure the element is in DOM, before destroying it.

Related to:
https://github.com/angular/angular/issues/14252

### Steps to reproduce  

1. npm -g install ionic 
2. npm install
3. ionic serve
4. Click button "Show/Hide Chart"

### Result  
An error occurs.
TypeError: Cannot read property 'removeEventListener' of undefined

### Expected result  
No error should pop up.

### Attachments  

[zoombarTestCase.zip](https://github.com/IgniteUI/igniteui-angular-wrappers/files/1984040/zoombarTestCase.zip)

**Comment by ebeling** [comment]
For all who can't wait for bug fix here is a workaround, that works for me:
In IgControlBase.prototype.ngOnDestroy - function I inserted following:
`if (this._widgetName!= "igZoombar") { 
... content of function ....
}`
