### ISSUE TITLE
ig-text-editor is unaware the auto-fill happened and thus it does not send updates to the model

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular-wrappers#284]
### Description  
ig-text-editor is unaware the auto-fill happened and thus it does not send updates to the model.

### Steps to reproduce  

1. Unzip the attached my-app3.zip, "npm install" and "npm start".
2. Open IE11 or Firefox and enable its autofill functionality to store user name and password in forms.
3. Open http://localhost:4200, type "aaa" in "User Name" and "bbb" in "Password" and click "Login".
4. You'll see a prompt window which asks you whether or not you would like to store the user name and the password. Answer "Yes" to it.
5. Click twice on "User Name" text box. You'll see a drop down open.
6. Select "aaa" from the drop down. You'll see "Password" text box is automatically filled.
7. Click "Login".

### Result  
In the developer tool console, you'll see "Login: [aaa][null]".
This means that the property bound to the password ig-text-editor is null although the text box is filled in UI.

### Expected result  
In the developer tool console, you'll see "Login: [aaa][bbb]".
The property bound to the password ig-text-editor has the auto-filled value.

### Attachments  
[my-app3.zip](https://github.com/IgniteUI/igniteui-angular-wrappers/files/2265276/my-app3.zip)

**Comment by alexalex972** [comment]
Related to https://github.com/IgniteUI/ignite-ui/issues/1776

**Comment by dkamburov** [comment]
IgniteUI/ignite-ui#1776 is resolving the issue
