### ISSUE TITLE
igGrid AOT sample is throwing an error

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular-wrappers#301]
### Description  
igGrid AOT sample is throwing an error

### Steps to reproduce  

1. Go to http://igniteui.github.io/igniteui-angular-wrappers/samples/igGrid-AoT/igGrid-AoT.html
2. Observe browser console

### Result  
There is an exception:
Error
ZoneDelegate.invoke @ zone.js?main=browser:192
Zone.run @ zone.js?main=browser:85
(anonymous) @ zone.js?main=browser:451
ZoneDelegate.invokeTask @ zone.js?main=browser:225
Zone.runTask @ zone.js?main=browser:125
drainMicroTaskQueue @ zone.js?main=browser:357
ZoneTask.invoke @ zone.js?main=browser:297

### Expected result  
There should be no exception.

**Comment by dkamburov** [comment]
We don't have that sample any more, `ng serve --aot` will run all of the sample in AOT
